name = "steavpn"
main = "workers/index.ts"
compatibility_date = "2026-10-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "steavpn-db"
database_id = "2d07880c-69a4-4fe6-9ebe-aa10f99d6916"

[[kv_namespaces]]
binding = "SESSIONS"
id = "f2b766679933419485c7ccd33d012233"

[vars]
ADMIN_ORIGIN = "https://steavpn.stea.africa"

[observability]
enabled = true
